Added payloadData
shortcut/shortcut-foundation-ios pull request #52
Opened 2022-07-04 10:00 UTC by HripsimeMartirosyan1990

2022-10-14 09:41 UTC, lemonandlime requested changes

2022-10-14 09:41 UTC, lemonandlime commented on Sources/ShortcutFoundation/Extensions/String+Extension.swift
> +        case .dayMonth: return "dd/MM"
This does not feel like standarlized date formats.

2022-10-14 09:41 UTC, lemonandlime commented on Sources/ShortcutFoundation/Core/Network/Core/Calls/NetworkingClient+NetworkingJSONDecodable.swift
> +    func get<ResponsePayload: Decodable, Payload: Encodable, errorPeyload: Encodable>(_ route: String, params: Payload, error: errorPeyload) -> NetworkPublisher<ResponsePayload> {
typo: `errorPeyload`

2022-10-14 09:41 UTC, lemonandlime commented on Sources/ShortcutFoundation/Core/Network/Core/Calls/NetworkingClient+NetworkingJSONDecodable.swift
> +    func get<ResponsePayload: Decodable, Payload: Encodable, errorPeyload: Encodable>(_ route: String, params: Payload, error: errorPeyload) -> NetworkPublisher<ResponsePayload> {
Also I do not want to send this in to all my requests. so you will have to create an overload.

2022-10-14 09:42 UTC, lemonandlime commented
Since this is not something that happens all the time that you need to decode error payload. Maybe we should just add it to the error as `Data` if it exists. Then we would not need to send in all that stuff in the init method of the get function. TYou could just check the throwing error if the network call fails and if you get data then manually decode to whatever type you expect to get in that case

2022-10-31 21:18 UTC, lemonandlime commented
@HripsimeMartirosyan1990 What do you say can we close this or do you wanna fix the issues the PR is getting a bit old.

2022-11-01 08:21 UTC, HripsimeMartirosyan1990 commented
> @HripsimeMartirosyan1990 What do you say can we close this or do you wanna fix the issues the PR is getting a bit old.

@lemonandlime those changes is used in Pangeo maybe we still need them to be merged

2023-10-11 08:56 UTC, closed without merging