Make Loggable take autoclosure
shortcut/shortcut-foundation-ios pull request #64
Opened 2023-02-27 16:40 UTC by Eskils

In summary, this is a very rarely needed performance optimization.

This feature makes Loggable take arguments as `@autoclosure`. Autoclosure is syntactic sugar for the compiler to convert expressions into a closure before passing them as an argument to the function. In effect, this delays the *execution* of the logged statement until it is being logged, or for `silent` verbosity, the expression is never made.

This does not make a big difference for simple logs such as:
```swift
logger.log(message: "Hello World!")
```

However it makes a big difference if a heavy computation is performed in the log, for instance:
```swift
logger.log(message: "\(bigArray.map { $0.heavyComputation() } )")
logger.log(message: "All users: \(users.sorted())")
```

2023-02-27 17:18 UTC, lemonandlime requested changes
I like it 👍. But i would not remove the old method but instead make that function call this one so we will have booth options.

2023-02-27 17:19 UTC, lemonandlime approved these changes

2023-02-28 12:17 UTC, AndreasShortcut approved these changes
Nice :+1:

2023-02-28 15:45 UTC, Eskils commented
> I like it 👍. But i would not remove the old method but instead make that function call this one so we will have booth options.

@lemonandlime I added `logText(message:)` methods to the logger, but not sure if there is any advantage to this?

2023-03-02 08:31 UTC, merged